title: "Arka Ian Goswami"
description: "Research, notes, and other writing"
theme: minima
# Show these pages as top navigation (minima uses header_pages)
header_pages:
  - research.md
  - notes.md
  - other.md

